version: '3'

services:
  database:
    image: postgres:14
    container_name: crawler-database
    volumes:
      - /mnt/footballdata:/var/lib/postgresql/data
    ports:
      - ${DATABASE_EXPOSE_PORT}:5432
    env_file:
      - .env
  migration-tool:
    build: ./docker/migration-tool
    container_name: crawler-migration
    working_dir: /migration
    volumes:
    - ./migration:/migration
    env_file:
      - .env
    depends_on:
      - database
  compiler:
    image: golang:1.17-alpine
    container_name: crawler-compiler
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./:/app
      - compilecache:/go

volumes:
  compilecache: